package com.bettercooking;

import com.bettercooking.commands.CookingCommand;
import com.bettercooking.editor.RecipeEditorChatListener;
import com.bettercooking.editor.RecipeEditorListener;
import com.bettercooking.listeners.BlockListener;
import com.bettercooking.listeners.FoodEffectListener;
import com.bettercooking.listeners.InventoryListener;
import com.bettercooking.managers.RecipeEditorManager;
import com.bettercooking.managers.RecipeManager;
import com.bettercooking.managers.StationManager;
import org.bukkit.plugin.java.JavaPlugin;

public final class BetterCooking extends JavaPlugin {

    private RecipeManager recipeManager;
    private StationManager stationManager;
    private RecipeEditorManager recipeEditorManager;

    @Override
    public void onEnable() {
        saveDefaultConfig();
        // Merge keys added in newer versions into configs generated by older builds
        getConfig().options().copyDefaults(true);
        saveConfig();

        recipeManager = new RecipeManager(this);
        recipeManager.loadRecipes();

        stationManager = new StationManager(this);
        stationManager.load();

        recipeEditorManager = new RecipeEditorManager(this);

        registerListener(new BlockListener(this));
        registerListener(new InventoryListener(this));
        registerListener(new FoodEffectListener(this));
        registerListener(new RecipeEditorListener(this, recipeEditorManager));
        registerListener(new RecipeEditorChatListener(this, recipeEditorManager));

        var cookingCommand = getCommand("cooking");
        if (cookingCommand != null) cookingCommand.setExecutor(new CookingCommand(this));

        String stationId = getConfig().getString("cooking-station.block-id", "SMOKER");
        if (stationId.startsWith("nexo:")) {
            if (!isNexoEnabled()) {
                getLogger().warning("cooking-station.block-id '" + stationId
                        + "' needs Nexo, but Nexo isn't installed/enabled — no block will open the cooking GUI!");
            }
        } else if (org.bukkit.Material.matchMaterial(stationId) == null) {
            getLogger().warning("cooking-station.block-id '" + stationId
                    + "' is not a valid material — no block will open the cooking GUI!");
        }

        var fuels = getConfig().getConfigurationSection("fuel.items");
        getLogger().info("BetterCooking v" + getDescription().getVersion()
                + " enabled. Station block: " + stationId
                + ", fuels: " + (fuels != null ? fuels.getValues(false) : "built-in defaults"));
    }

    @Override
    public void onDisable() {
        // Close open station GUIs so their contents persist through the close handler
        for (org.bukkit.entity.Player player : getServer().getOnlinePlayers()) {
            if (player.getOpenInventory().getTopInventory().getHolder()
                    instanceof com.bettercooking.ui.CookingUI.StationHolder) {
                player.closeInventory();
            }
        }
        if (stationManager != null) stationManager.save();
        getLogger().info("BetterCooking disabled.");
    }

    public RecipeManager getRecipeManager() { return recipeManager; }
    public StationManager getStationManager() { return stationManager; }
    public RecipeEditorManager getRecipeEditorManager() { return recipeEditorManager; }

    /** True only when the Nexo plugin is actually installed and enabled — never assume from config alone. */
    public boolean isNexoEnabled() {
        return getServer().getPluginManager().isPluginEnabled("Nexo");
    }

    /**
     * Registers a listener on its own so one listener failing to resolve an event class
     * (e.g. a server build that doesn't match the API this plugin compiled against) logs
     * clearly and doesn't silently take every other listener down with it.
     */
    private void registerListener(org.bukkit.event.Listener listener) {
        try {
            getServer().getPluginManager().registerEvents(listener, this);
        } catch (Throwable t) {
            getLogger().severe("Failed to register listener " + listener.getClass().getSimpleName() + ": " + t);
        }
    }
}
